QUESTION 1

In [1]:
import numpy as np

# Task 1: Create a 2D array (4 branches × 6 months)
transactions = np.array([
    [1200, 1350, 1100, 1450, 1600, 1700],  
    [1000, 1250, 1300, 1400, 1500, 1600],  
    [900, 950, 1000, 1050, 1100, 1150],    
    [1500, 1550, 1600, 1650, 1700, 1750]   
])

# Task 2: Total transactions per branch
total_per_branch = np.sum(transactions, axis=1)

# Task 3: Branch with highest total transactions
highest_branch_index = np.argmax(total_per_branch)
highest_branch_total = total_per_branch[highest_branch_index]

# Task 4: Average monthly transaction volume across all branches
average_monthly_volume = np.mean(transactions)

# Task 5: Reshape to 3x8 and explain
reshaped = transactions.reshape(3, 8)
implication = "Reshaping changes the structure but not the data. It may lose the original branch/month meaning."


In [3]:
print(transactions)

[[1200 1350 1100 1450 1600 1700]
 [1000 1250 1300 1400 1500 1600]
 [ 900  950 1000 1050 1100 1150]
 [1500 1550 1600 1650 1700 1750]]


In [7]:
print(total_per_branch)

[8400 8050 6150 9750]


In [9]:
print(highest_branch_index)

3


In [13]:
print(highest_branch_total)

9750


In [15]:
print(average_monthly_volume)

1347.9166666666667


In [17]:

print(reshaped)

[[1200 1350 1100 1450 1600 1700 1000 1250]
 [1300 1400 1500 1600  900  950 1000 1050]
 [1100 1150 1500 1550 1600 1650 1700 1750]]


QUESTION 2

In [23]:
# Task 1: Create list of 10 delivery routes
routes = [
    "Nairobi-Kisumu", "Mombasa-Nairobi", "Eldoret-Nakuru", "Kisumu-Busia",
    "Nairobi-Eldoret", "Nakuru-Mombasa", "Busia-Kakamega", "Kakamega-Kisii",
    "Nairobi-Thika", "Thika-Garissa"
]
print(routes)

['Nairobi-Kisumu', 'Mombasa-Nairobi', 'Eldoret-Nakuru', 'Kisumu-Busia', 'Nairobi-Eldoret', 'Nakuru-Mombasa', 'Busia-Kakamega', 'Kakamega-Kisii', 'Nairobi-Thika', 'Thika-Garissa']


In [25]:
# Task 2: Append new route and remove discontinued one
routes.append("Garissa-Wajir")
print(routes)


['Nairobi-Kisumu', 'Mombasa-Nairobi', 'Eldoret-Nakuru', 'Kisumu-Busia', 'Nairobi-Eldoret', 'Nakuru-Mombasa', 'Busia-Kakamega', 'Kakamega-Kisii', 'Nairobi-Thika', 'Thika-Garissa', 'Garissa-Wajir']


In [27]:
routes.remove("Kisumu-Busia")
print(routes)

['Nairobi-Kisumu', 'Mombasa-Nairobi', 'Eldoret-Nakuru', 'Nairobi-Eldoret', 'Nakuru-Mombasa', 'Busia-Kakamega', 'Kakamega-Kisii', 'Nairobi-Thika', 'Thika-Garissa', 'Garissa-Wajir']


In [29]:
# Task 3: Sort alphabetically and reverse
routes.sort()
print(routes)

['Busia-Kakamega', 'Eldoret-Nakuru', 'Garissa-Wajir', 'Kakamega-Kisii', 'Mombasa-Nairobi', 'Nairobi-Eldoret', 'Nairobi-Kisumu', 'Nairobi-Thika', 'Nakuru-Mombasa', 'Thika-Garissa']


In [31]:
routes.reverse()
print(routes)

['Thika-Garissa', 'Nakuru-Mombasa', 'Nairobi-Thika', 'Nairobi-Kisumu', 'Nairobi-Eldoret', 'Mombasa-Nairobi', 'Kakamega-Kisii', 'Garissa-Wajir', 'Eldoret-Nakuru', 'Busia-Kakamega']


In [33]:
# Task 4: Count routes starting with "N"
count_N = sum(route.startswith("N") for route in routes)
print(count_N)

4


In [35]:
# Task 5: List comprehension for routes longer than 10 characters
long_routes = [route for route in routes if len(route) > 10]
print(long_routes)

['Thika-Garissa', 'Nakuru-Mombasa', 'Nairobi-Thika', 'Nairobi-Kisumu', 'Nairobi-Eldoret', 'Mombasa-Nairobi', 'Kakamega-Kisii', 'Garissa-Wajir', 'Eldoret-Nakuru', 'Busia-Kakamega']


QUESTION 3

In [39]:
# Task 1: Create patient tuple
patient = ("John Doe", 45, "120/80", 72)


In [41]:
# Task 2: Access age and heart rate
age = patient[1]
heart_rate = patient[3]
print(age,heart_rate)

45 72


In [43]:
# Task 4: Update heart rate
patient_list = list(patient)

print(patient_list)

['John Doe', 45, '120/80', 72]


In [45]:
patient_list[3] = 75
print(patient_list)

['John Doe', 45, '120/80', 75]


In [49]:
updated_patient = tuple(patient_list)
print(updated_patient)

('John Doe', 45, '120/80', 75)


In [51]:
# Task 5: Tuple of 5 patients and extract names
patients = (
    ("Alice", 30, "110/70", 68),
    ("Bob", 40, "120/80", 72),
    ("Charlie", 35, "115/75", 70),
    ("Diana", 50, "130/85", 76),
    ("Eve", 28, "105/65", 65)
)
names = [p[0] for p in patients]

In [53]:
print(names)

['Alice', 'Bob', 'Charlie', 'Diana', 'Eve']


QUESTION 

In [67]:
# Task 1: Create dictionary
inventory = {
    "Laptop": 15,
    "Phone": 8,
    "Tablet": 12,
    "Headphones": 5,
    "Charger": 20
}
print(inventory)

{'Laptop': 15, 'Phone': 8, 'Tablet': 12, 'Headphones': 5, 'Charger': 20}


In [69]:
# Task 2: Add new product and update quantity
inventory["Smartwatch"] = 10

print(inventory)

{'Laptop': 15, 'Phone': 8, 'Tablet': 12, 'Headphones': 5, 'Charger': 20, 'Smartwatch': 10}


In [71]:
inventory["Phone"] = 12
print(inventory)

{'Laptop': 15, 'Phone': 12, 'Tablet': 12, 'Headphones': 5, 'Charger': 20, 'Smartwatch': 10}


In [73]:
# Task 3: Function to return products with stock < 10
def low_stock_items(inv):
    return {product: qty for product, qty in inv.items() if qty < 10}


In [75]:
# Task 4: Delete discontinued product and display updated dictionary
del inventory["Headphones"]
print(inventory)

{'Laptop': 15, 'Phone': 12, 'Tablet': 12, 'Charger': 20, 'Smartwatch': 10}


In [77]:
# Task 5: Loop through and print each product with quantity
for product, qty in inventory.items():
    print(f"{product}: {qty}")

Laptop: 15
Phone: 12
Tablet: 12
Charger: 20
Smartwatch: 10
